### ISSUE TITLE
Features that I feel are missing to help out trading loot.

### ISSUE THREAD

**Issue by KurtzPT** [BoxximusPrime/WhoGotLoots#3]
While trying to find a replacement for gmLm (another loot monitor addon) I found your addon! It's looking great but I have some suggestions:

- Add a button where one can automatically send a whisper message to the person who got the loot, asking "if they need it/want to trade?". Bonus points if one can costumize the message itself.
- Another button where one can inspect the person who got the loot. My reason behind this is that sometimes I don't want to bother people when they have equipped a worse item that what they got, but in the middle of the raid/dungeon, sometimes is hard to inspect. (We do have the itemlvl comparison, which helps but sometimes it does not show)
- More options, maybe a filter where only loot above a certain quality will be showed (epic+)
- Maybe a trade button?

**Comment by BoxximusPrime** [comment]
Hey there! Glad you're liking the addon, it's my first one so bear with me haha.
- First one, I've thought about but undecided. Sometimes getting automated whispers from people with other similar addons can get kind of bothersome, but I have have considered it.
- Love the inspect idea. Maybe an alt + left click or something, to cut down on the number of UI elements. I'm also considering removing the control hints from the item boxes, since I have an information button now, undecided on that one
- Quality filter is thought I also had but wasn't sure, but can implement easily enough
- Same as the inspect button, can prob do.

**Comment by KurtzPT** [comment]
> Hey there! Glad you're liking the addon, it's my first one so bear with me haha.
> 
> * First one, I've thought about but undecided. Sometimes getting automated whispers from people with other similar addons can get kind of bothersome, but I have have considered it.
> * Love the inspect idea. Maybe an alt + left click or something, to cut down on the number of UI elements. I'm also considering removing the control hints from the item boxes, since I have an information button now, undecided on that one
> * Quality filter is thought I also had but wasn't sure, but can implement easily enough
> * Same as the inspect button, can prob do.

For the first point, I didn't mean to be automated whenever something drops, but a shortcut or button to make that message. similar to the other points, sometimes is very hard to find the person in the middle of the raid to target it and message :)

**Comment by BoxximusPrime** [comment]
Ended up adding a whisper feature, will be in next release after some RC testing
