### ISSUE TITLE
WhoGotLoots does not work in mythic plus.

### ISSUE THREAD

**Issue by KurtzPT** [BoxximusPrime/WhoGotLoots#9]
As title says, I don't think I ever saw WGL showing the loot someone got on the end of a key.

**Comment by BoxximusPrime** [comment]
Do you have "hide unequippable" turned on? - Which reminds me, I should prob have that off by default instead of on.

**Comment by KurtzPT** [comment]
I do have it turned on, but I'm assuming it should still show loot that I can equip, but I'm almost sure it doesn't show.

I'll report back later today after I do some more mythics plus

**Comment by BoxximusPrime** [comment]
That option will make the item not show if it's not you looting it and either you can't equip it, it's not appropriate for you, or it doesn't have main stat (and it's not a ring, trinket, or cloak). I do see potentially an issue I have though with the logic on rings and trinkets, forgot to bypass those since they don't always have main stat.

If it happens again, let me know what class and spec you're playing, and what the item was, and of course check for any lua errors. I have a big database of every class and their spec, and a value on whether the item type is good for that class, bad for that class, or literally not usable and it's entirely possible I got a value wrong on the database cause it was a LOT of work haha.

Appreciate the reports, btw!

**Comment by KurtzPT** [comment]
So my previous comment was not correct, it does in fact work, but sometimes it does not report everything. I had an issue with a ring not being reported:

![image](https://github.com/user-attachments/assets/4e72d1ae-97c9-4507-bf13-fe2e7b391168)

I was playing a DK Unholy when the above dropped to another player.

**Comment by BoxximusPrime** [comment]
Did you have hide unequipable enabled when the ring didn't show? I may have found a bug for that specific case with rings and trinkets.

**Comment by KurtzPT** [comment]
> Did you have hide unequipable enabled when the ring didn't show? I may have found a bug for that specific case with rings and trinkets.

Yes I had it enabled.

**Comment by BoxximusPrime** [comment]
Pushing an update now, lemme know if that seems to fix it.

**Comment by KurtzPT** [comment]
Forgot to update, for now it seems to be working fine, I didn't see any situation where it didn't show me the loot correctly. Thanks!
